### ISSUE TITLE
Install mpicc?

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/hpc-tools#2]
Hi! I'm trying to install intel MPI (runtime and compiler) but I can't seem to find mpicc. I'm doing:

```
google_mpi_tuning --nosmt
google_install_mpi --intel_mpi
```
I noticed in your tutorial you are using spack to install it, which might possible be a warning that you aren't provisioning it here.  https://github.com/GoogleCloudPlatform/batch-samples/tree/d026683aa27d01111ec68a66d07abadab1712730/wrf. If I'm missing it, could you give me a pointer? And if not, how do you expect the user to compile MPI code beforehand?

**Comment by vsoch** [comment]
Related - I was able to get mpicc y using `google_install_intelmpi` but ran into another issue, I reported here: https://github.com/GoogleCloudPlatform/batch-samples/issues/29 but realize here might have been the better place!

**Comment by vsoch** [comment]
I found this issue https://stackoverflow.com/questions/33780992/mpirun-unrecognized-argument-mca that suggests it might be a mix up of MPI implementations.

**Comment by hanghu** [comment]
Just took a look at your `setup.sh` script, and one thing maybe you can try is to source the intel mpi's `var.sh` before running `mpicc` and `mpirun`.

For example add a line as:
```
source <intelmpi-installation-dir>/mpi/latest/env/vars.sh
```
replace the `<intelmpi-installation-dir>` with path where your intelmpi is installed (seems to be `/opt/intel/` from your script.)

> Related - I was able to get mpicc y using `google_install_intelmpi` but ran into another issue, I reported here: [GoogleCloudPlatform/batch-samples#29](https://github.com/GoogleCloudPlatform/batch-samples/issues/29) but realize here might have been the better place!

**Comment by vsoch** [comment]
Ah! You know I saw it echoed in the logs, and I assumed that meant it was run! But it looks like it's added as a message of the day? https://github.com/GoogleCloudPlatform/hpc-tools/blob/24dcc7be275c4b40c4479c52f35bc877cb1c5f8a/centos_7/google_install_intelmpi#L144-L153 Lol, oh no, I totally missed that!

@hanghu now it works!!

![image](https://github.com/GoogleCloudPlatform/hpc-tools/assets/814322/85914fd8-195c-4b1c-ab4e-58b043e559ec)

Since this will be run many times headless, could we please have an option that would install and source that path? Just having the option (and then showing an example usage) will likely save folks (that are running headlessly and assume seeing the source means it was run) many hours/days of pain! :laughing:

**Comment by hanghu** [comment]
Hi @vsoch, glad it works. So I think the variables are environmental runtime variables.  If you would like to source them you by default, you can added it to `~/.bashrc`. It would be hard to make an option on the other hand, since it depends on the path where the intel mpi is installed. One thing we can do to make it easier is to add some instructions in the `README.md`, and I will do that in our next update.

**Comment by vsoch** [comment]
That sounds perfect - thank you @hanghu for your help!
