### ISSUE TITLE
Issue with yum group install Development Tools for libfabric

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/hpc-tools#3]
I think there might be a bug in the capture of this as a list here:

https://github.com/GoogleCloudPlatform/hpc-tools/blob/24dcc7be275c4b40c4479c52f35bc877cb1c5f8a/rocky_linux_8/google_hpc_libfabric#L55-L57

When it is used here:

https://github.com/GoogleCloudPlatform/hpc-tools/blob/24dcc7be275c4b40c4479c52f35bc877cb1c5f8a/rocky_linux_8/google_hpc_libfabric#L115-L125

It appears to break into two pieces, and I get:

```console
Last metadata expiration check: 0:09:47 ago on Tue Sep  5 00:51:23 2023.
Module or Group 'tools' is not available.
```
For now I'm just doing:

```bash
yum groupinstall -y "Development tools"
```
Thanks!

**Comment by vsoch** [comment]
And a few more possible runs - the help says the default install dir is `/opt/Libfabric` (capital L) but it turns to lowercase:

```
# ls /opt/libfabric/
libnet-fi.so  libpsm3-fi.so  libpsm3-fi.so.1.19.0
```
And then the `--dryrun` flag just shows the help. I already installed it so this might be that, but maybe there could still be checks.

```
[root@f04be33ce02d rocky_linux_8]# ./google_hpc_libfabric --dryrun
  Usage:
    Verify installation steps: google_hpc_libfabric [options] --dryrun
    Apply installation: google_hpc_libfabric [options]

  Options:
    -h | --help          Display help message
    --dryrun             Do not execute commands
    --net                Build the Libfabric NET Provider
    --psm3               Build the Libfabric PSM3 Provider
    --install_dir        Configure the prefix directory for installations 
                         Default location is set to /opt/Libfabric
    --cleanup            Remove the downloaded source code in /tmp/src_download/
```

**Comment by rohitramu** [comment]
These issues have been fixed now, thanks for the report.

**Comment by vsoch** [comment]
Thanks for the fix!
